# Streamlit Cloud Deployment

name: ga-analytics-ai
python_version: 3.10.8

[server]
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[client]
toolbarMode = "minimal"
showErrorDetails = false
